#!/usr/bin/env bash

# VLP - Stage1 (Pretrained)
GPU_DEVICE="0,1,2,3,4,5,6,7"
length=${#GPU_DEVICE}
port=$(($RANDOM%10000+30000))
n_gpu=$(((length+1)/2))
image_bath=2
test_batch=2
image_resol=1024

CUDA_VISIBLE_DEVICES=$GPU_DEVICE mpirun -n $n_gpu python entry.py train \
            --conf_files configs/step1.yaml \
            --overrides \
            FP16 True \
            PORT $port \
            WANDB True \
            MODEL.DECODER.CAPTIONING.ENABLED True \
            MODEL.DECODER.RETRIEVAL.ENABLED True \
            MODEL.DECODER.GROUNDING.ENABLED True \
            MODEL.DECODER.CAPTIONING_WEIGHT 8 \
            MODEL.DECODER.RETRIEVAL_WEIGHT 8 \
            MODEL.DECODER.TOP_CAPTIONING_LAYERS 3 \
            MODEL.DECODER.TOP_RETRIEVAL_LAYERS 3 \
            MODEL.DECODER.TOP_GROUNDING_LAYERS 6 \
            MODEL.DECODER.GROUNDING.TEXT_WEIGHT 2.0 \
            MODEL.DECODER.GROUNDING.CLASS_WEIGHT 0.5 \
            COCO.INPUT.IMAGE_SIZE $image_resol \
            COCO.TRAIN.BATCH_SIZE_TOTAL $((n_gpu * image_bath)) \
            COCO.TRAIN.BATCH_SIZE_PER_GPU $image_bath \
            COCO.TEST.BATCH_SIZE_TOTAL $((n_gpu * test_batch)) \
            REF.TEST.BATCH_SIZE_TOTAL $n_gpu \
            ADE20K.TEST.BATCH_SIZE_TOTAL $((n_gpu * test_batch)) \
            WEIGHT True \
            RESUME_FROM /home/junho/lbk/seem_samvitb_v1.pt
            # /home/junho/lbk/seem_samvitb_v1.pt
            # /mnt/ssd/lbk-cvpr/syslearner/run_2/default/epoch1/syslearner.pt
            # /mnt/ssd/lbk-cvpr/checkpoints/seem_samvitb_v1.pt
            # /mnt/ssd/lbk-cvpr/syslearner/run_91/default/epoch1
            # /mnt/ssd/lbk-cvpr/syslearner/run_9/default/epoch2/syslearner.pt
            # /mnt/ssd/lbk-cvpr/checkpoints/xdecoder_focall_last.pt
            # /mnt/ssd/lbk-cvpr/checkpoints/focalt_in21k_yfcc_gcc_xdecoder_unicl.pt
            # /mnt/ssd/lbk-cvpr/syslearner/Syslearner_ckpt/default/epoch1_model_state_dict.pt



# RefCOCO
# GPU_DEVICE="0,1,2,3,4,5"
# length=${#GPU_DEVICE}
# port=$(($RANDOM%10000+30000))
# n_gpu=$(((length+1)/2))
# image_bath=8
# test_batch=4

# CUDA_VISIBLE_DEVICES=$GPU_DEVICE mpirun -n $n_gpu python entry.py train \
#             --conf_files configs/step1_finetune_refcoco.yaml \
#             --overrides \
#             FP16 True \
#             PORT $port \
#             WANDB True \
#             MODEL.DECODER.CAPTIONING.ENABLED True \
#             MODEL.DECODER.RETRIEVAL.ENABLED True \
#             MODEL.DECODER.GROUNDING.ENABLED True \
#             MODEL.DECODER.CAPTIONING_WEIGHT 8 \
#             MODEL.DECODER.RETRIEVAL_WEIGHT 8 \
#             MODEL.DECODER.TOP_CAPTIONING_LAYERS 3 \
#             MODEL.DECODER.TOP_RETRIEVAL_LAYERS 3 \
#             MODEL.DECODER.TOP_GROUNDING_LAYERS 6 \
#             MODEL.DECODER.GROUNDING.TEXT_WEIGHT 2.0 \
#             MODEL.DECODER.GROUNDING.CLASS_WEIGHT 0.5 \
#             COCO.TRAIN.BATCH_SIZE_TOTAL $((n_gpu * image_bath)) \
#             COCO.TRAIN.BATCH_SIZE_PER_GPU $image_bath \
#             REF.TEST.BATCH_SIZE_TOTAL $((n_gpu * test_batch)) \
#             WEIGHT True \
#             RESUME_FROM /mnt/ssd/lbk-cvpr/syslearner/Syslearner_ckpt/default/epoch3_model_state_dict.pt
#             # /home/junho/lbk/sam_xdecoder/ckpt/run_5/default/epoch1_model_state_dict.pt
#             # /mnt/ssd/lbk-cvpr/checkpoints/xdecoder_focall_last.pt
#             # /mnt/ssd/lbk-cvpr/checkpoints/focalt_in21k_yfcc_gcc_xdecoder_unicl.pt
#             # /mnt/ssd/lbk-cvpr/syslearner/Syslearner_ckpt/default/epoch1_model_state_dict.pt


# INSTRUCTION
# GPU_DEVICE="0,1,2,3,4,5,6,7"
# length=${#GPU_DEVICE}
# n_gpu=$(((length+1)/2))
# port=$(($RANDOM%10000+30000))
# lang_batch=6
# test_batch=4

# CUDA_VISIBLE_DEVICES=$GPU_DEVICE mpirun -n $n_gpu python entry.py train \
#             --conf_files configs/step2_instruction.yaml \
#             --overrides \
#             FP16 True \
#             PORT $port \
#             WANDB True \
#             MODEL.DECODER.CAPTIONING.ENABLED True \
#             MODEL.DECODER.RETRIEVAL.ENABLED True \
#             MODEL.DECODER.GROUNDING.ENABLED True \
#             MODEL.DECODER.CAPTIONING_WEIGHT 8 \
#             MODEL.DECODER.RETRIEVAL_WEIGHT 8 \
#             MODEL.DECODER.TOP_CAPTIONING_LAYERS 3 \
#             MODEL.DECODER.TOP_RETRIEVAL_LAYERS 3 \
#             MODEL.DECODER.TOP_GROUNDING_LAYERS 6 \
#             MODEL.DECODER.GROUNDING.TEXT_WEIGHT 2.0 \
#             MODEL.DECODER.GROUNDING.CLASS_WEIGHT 0.5 \
#             INSTRUCT.TRAIN.BATCH_SIZE_TOTAL $((n_gpu * lang_batch)) \
#             INSTRUCT.TRAIN.BATCH_SIZE_PER_GPU $lang_batch \
#             REF.TEST.BATCH_SIZE_TOTAL $((n_gpu * test_batch)) \
#             VLP.TEST.BATCH_SIZE_TOTAL $((n_gpu * test_batch)) \
#             WEIGHT True \
#             RESUME_FROM /mnt/ssd/lbk-cvpr/syslearner/Syslearner_ckpt/default/epoch3_model_state_dict.pt
#             # /home/junho/lbk/sam_xdecoder/ckpt/run_5/default/epoch1_model_state_dict.pt
#             # /mnt/ssd/lbk-cvpr/checkpoints/xdecoder_focall_last.pt
#             # /mnt/ssd/lbk-cvpr/checkpoints/focalt_in21k_yfcc_gcc_xdecoder_unicl.pt
#             # /mnt/ssd/lbk-cvpr/syslearner/Syslearner_ckpt/default/epoch1_model_state_dict.pt


# INSTRUCTION
# GPU_DEVICE="0,1,2,3,4,5,6,7"
# length=${#GPU_DEVICE}
# n_gpu=$(((length+1)/2))
# port=$(($RANDOM%10000+30000))
# lang_batch=6
# test_batch=4

# CUDA_VISIBLE_DEVICES=$GPU_DEVICE mpirun -n $n_gpu python entry.py train \
#             --conf_files configs/step2_instruction.yaml \
#             --overrides \
#             FP16 True \
#             PORT $port \
#             WANDB True \
#             MODEL.DECODER.CAPTIONING.ENABLED True \
#             MODEL.DECODER.RETRIEVAL.ENABLED True \
#             MODEL.DECODER.GROUNDING.ENABLED True \
#             MODEL.DECODER.CAPTIONING_WEIGHT 8 \
#             MODEL.DECODER.RETRIEVAL_WEIGHT 8 \
#             MODEL.DECODER.TOP_CAPTIONING_LAYERS 3 \
#             MODEL.DECODER.TOP_RETRIEVAL_LAYERS 3 \
#             MODEL.DECODER.TOP_GROUNDING_LAYERS 6 \
#             MODEL.DECODER.GROUNDING.TEXT_WEIGHT 2.0 \
#             MODEL.DECODER.GROUNDING.CLASS_WEIGHT 0.5 \
#             INSTRUCT.TRAIN.BATCH_SIZE_TOTAL $((n_gpu * lang_batch)) \
#             INSTRUCT.TRAIN.BATCH_SIZE_PER_GPU $lang_batch \
#             REF.TEST.BATCH_SIZE_TOTAL $((n_gpu * test_batch)) \
#             VLP.TEST.BATCH_SIZE_TOTAL $((n_gpu * test_batch)) \
#             WEIGHT True \
#             RESUME_FROM /mnt/ssd/lbk-cvpr/syslearner/Syslearner_ckpt/default/epoch3/syslearner.pt

# VQA Eval
# GPU_DEVICE="0,1,2,3,4,5,6,7"
# length=${#GPU_DEVICE}
# n_gpu=$(((length+1)/2))
# port=$(($RANDOM%10000+30000))
# lang_batch=6
# test_batch=4

# CUDA_VISIBLE_DEVICES=$GPU_DEVICE mpirun -n $n_gpu python lbk_entry.py evaluate  \
#             --conf_files configs/step2_instruction.yaml \
#             --overrides \
#             FP16 True \
#             PORT $port \
#             WANDB False \
#             MODEL.DECODER.CAPTIONING.ENABLED True \
#             MODEL.DECODER.RETRIEVAL.ENABLED True \
#             MODEL.DECODER.GROUNDING.ENABLED True \
#             MODEL.DECODER.CAPTIONING_WEIGHT 8 \
#             MODEL.DECODER.RETRIEVAL_WEIGHT 8 \
#             MODEL.DECODER.TOP_CAPTIONING_LAYERS 3 \
#             MODEL.DECODER.TOP_RETRIEVAL_LAYERS 3 \
#             MODEL.DECODER.TOP_GROUNDING_LAYERS 6 \
#             MODEL.DECODER.GROUNDING.TEXT_WEIGHT 2.0 \
#             MODEL.DECODER.GROUNDING.CLASS_WEIGHT 0.5 \
#             COCO.TEST.BATCH_SIZE_TOTAL 8 \
#             COCO.TRAIN.BATCH_SIZE_TOTAL 8 \
#             COCO.TRAIN.BATCH_SIZE_PER_GPU 1 \
#             VLP.TEST.BATCH_SIZE_TOTAL 8 \
#             VLP.TRAIN.BATCH_SIZE_TOTAL 8 \
#             VLP.TRAIN.BATCH_SIZE_PER_GPU 1 \
#             VQA.TEST.BATCH_SIZE_TOTAL $((n_gpu * test_batch)) \
#             WEIGHT True \
#             RESUME_FROM /mnt/ssd/lbk-cvpr/syslearner/Syslearner_ckpt/default/epoch3/syslearner.pt
